on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: render-qmds.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render GitHub README
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: markdown_github
          path: README.qmd
