on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: render-qmds.yaml

permissions: read-all

jobs:
  github-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::rmarkdown
            any::knitr

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render GitHub README
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ./README.qmd
